### ISSUE TITLE
Generate bootlogo for colour changing, along with charge screen and load screen

### ISSUE THREAD

**Issue by hmcneill46** [hmcneill46/muOS-MinUIfied-Theme-Generator#14]
This is something I am excited to get into, but haven't started yet.

The goal is to not need any template images at all, and generate them all from scratch by running the program. This would also make the boot logo prettier.

**Comment by GrumpyGopher** [comment]
Would be good if this could use the background image if it is specified

**Comment by hmcneill46** [comment]
This issue was fixed in commits:
4cab0222c5f1f7ddc492f3ca9fd20368918eb750
e3ff0e0e0343b5960d4dfed45b741d4fed9bf044
e4a165f7209d004db49e98e7edc91d0559593d2d
