### ISSUE TITLE
Add option for 'Show console name at top' to take folder name and not muOSSystemName

### ISSUE THREAD

**Issue by lcoiffard** [hmcneill46/muOS-MinUIfied-Theme-Generator#32]
When I check 'Show console name at top', it takes muOSSystemName but I would like to take folder name.
For example, I have a folder NEC PC Engine CD for roms but it's related to NEC PC Engine supergrafx for system name (box art).

**Comment by hmcneill46** [comment]
I'll look into this tomorrow, cheers for posting!

**Comment by hmcneill46** [comment]
This is fixed with commit fa00207090a9dfd16bd2b99202ce764593924b56

**Comment by lcoiffard** [comment]
Thank you :)
